sudo: required
langugae: generic
services:
  - docker

before_install:
  - docker build -t anooradhamk/complex-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=True anooradhamk/complex-react npm test
after_success:
  after_success:
  - if [ -n "$DOCKER_PASSWORD" ]; then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin;
      docker push anooradhamk/multi-client;
      docker push anooradhamk/multi-nginx;
      docker push anooradhamk/multi-server;
      docker push anooradhamk/multi-worker;
    else
      echo "DOCKER_PASSWORD is empty! Check Travis CI settings.";
    fi
